**Creating tensors**

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

TensorFlow 2.x selected.
<module 'tensorflow_core._api.v2.version' from '/tensorflow-2.1.0/python3.6/tensorflow_core/_api/v2/version/__init__.py'>


In [0]:
string = tf.Variable("this is a string" , tf.string)

In [4]:
print(string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>


In [0]:
integer = tf.Variable(543 , tf.int16)

In [7]:
print(integer)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=543>


In [0]:
float_val = tf.Variable(45.69 , tf.float64)

In [9]:
print(float_val)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=45.69>


**Rank/Degree of tensor**




number of dimensions involved in tensor



dimension 0 means scalar
more than 1 means vector

In [0]:
rank1_tensor = tf.Variable(["hello" , "tim" , "here"] , tf.string)

In [0]:
rank2_tensor = tf.Variable([["hello" , "tim"],["i" , "here"]] , tf.string)

to determine rank of a tensor, we can call the following method

In [12]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [13]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

**Shape of tensor**

number of elements that exist in each dimension

In [14]:
tf.shape(rank1_tensor)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [15]:
tf.shape(rank2_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

**Changing Shape**

number of elements in a tensor is equal to the product of sizes of all its shapes



In [0]:
tensor1 = tf.ones([1,2,3])

In [17]:
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)




The following function is used to change the shape

In [0]:
tensor2 = tf.reshape(tensor1 , [2,3,1])

In [19]:
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [0]:
tensor3 = tf.reshape(tensor1 , [3,-1])

In [21]:
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


**Slicing**

In [0]:
matrix = [
          [1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]
]

In [0]:
tensor = tf.Variable(matrix , dtype=tf.int32)

In [28]:
print(tensor)

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)>


In [29]:
print(matrix)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]


In [30]:
print(tf.rank(tensor))

tf.Tensor(2, shape=(), dtype=int32)


In [34]:
print(tf.shape(tensor))

tf.Tensor([4 5], shape=(2,), dtype=int32)


In [0]:
three = tensor[0,2] #3rd element from 1st row

In [38]:
print(three)

tf.Tensor(3, shape=(), dtype=int32)


In [0]:
row1 = tensor[0] #selects first column

In [42]:
print(row1)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [0]:
column_1_in_row_2_and_3 = tensor[1:3,0] #selects column 1 in row 2 and 3

In [46]:
print(column_1_in_row_2_and_3)

tf.Tensor([ 6 11], shape=(2,), dtype=int32)


**Types of Tensors**



*   Variable
*   Constant
*   Placeholder
*   SparseTensor


all tensors are immutable except Variable.

